apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJWakNCL3FBREFnRUNBZ0VBTUFvR0NDcUdTTTQ5QkFNQ01DTXhJVEFmQmdOVkJBTU1HR3N6Y3kxelpYSjIKWlhJdFkyRkFNVFU1T0RJMU56WXlNREFlRncweU1EQTRNalF3T0RJM01EQmFGdzB6TURBNE1qSXdPREkzTURCYQpNQ014SVRBZkJnTlZCQU1NR0dzemN5MXpaWEoyWlhJdFkyRkFNVFU1T0RJMU56WXlNREJaTUJNR0J5cUdTTTQ5CkFnRUdDQ3FHU000OUF3RUhBMElBQk5KVldObGhoQ1JXMGJlNW9yeWEzWWpCRVB0L3g0T2N3WG01OUpPT3hRRjUKbTUzNzUyeWF6YzMwN3VxSWNzUUVvVS93bnhuTWZZdmtXSE1ldUQwc2dIT2pJekFoTUE0R0ExVWREd0VCL3dRRQpBd0lDcERBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUFvR0NDcUdTTTQ5QkFNQ0EwY0FNRVFDSUNTQ2ZMRlgxWFA1Ck01TDJCbmpVVFlBamhsa0tuUlpRRE5XOUZMTm5FeDFPQWlBaG00Mnl6M2xDL2lrL2MvTmhKYTFYbXdpZGJSWnYKT1FtWGk0ZGxDU3hXTkE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://127.0.0.1:6443
  name: default
contexts:
- context:
    cluster: default
    user: default
  name: default
current-context: default
kind: Config
preferences: {}
users:
- name: default
  user:
    password: a2794179a051c3422ba865f5eb382082
    username: admin
